backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources "insurances", only: %i[index show] do
    resources :subscriptions, only: [:create]
  end

  namespace :admin do
    resources :insurances
    resources :claims, only: %i[index edit update]
    resources :discount_codes, only: %i[index new create]
    resources :subscriptions, only: %i[index]
  end

  namespace :api do
    resources :insurances, only: [:index]
  end

  resources :companies

  resources :subscriptions, only: %i[index] do
    resources :claims, only: %i[new create]
  end

  resources :claims, only: [:index]

  resources :vets, only: %i[index update show] do
    resources :scheduled_appointments, only: [:create]
    resources :prescriptions, only: %i[new create]
  end

  get "payments/validate_payment"

  get "payments/success"
  get "payments/error"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "insurances#index"
end

backend/app/models/insurance.rb
# frozen_string_literal: true

class Insurance < ApplicationRecord
  has_many :subscriptions, dependent: :destroy
  has_many :discount_codes, dependent: :destroy
  has_many :vets, dependent: :destroy
  belongs_to :company

  validates :name, presence: true, uniqueness: true
  validates :price_cents, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

backend/app/controllers/admin/insurances_controller.rb
# frozen_string_literal: true

module Admin
  class InsurancesController < ApplicationController
    before_action :authorize_admin!

    def index
      @insurances = Insurance.all
    end

    def show
      @insurance = Insurance.find(params[:id])
    end

    def new
      @insurance = Insurance.new
    end

    def edit
      @insurance = Insurance.find(params[:id])
    end

    def create
      @insurance = Insurance.new(insurance_params)
      if @insurance.save
        redirect_to [:insurances, @insurances], notice: t("admin.insurances.created")
      else
        render :new
      end
    end

    def update
      @insurance = Insurance.find(params[:id])
      if @insurance.update(insurance_params)
        redirect_to admin_insurances_path, notice: t("admin.insurances.updated")
      else
        render :edit
      end
    end

    def destroy
      @insurance = Insurance.find(params[:id])
      @insurance.destroy
      redirect_to admin_insurances_path, notice: t("admin.insurances.deleted")
    end

    private

    def insurance_params
      params.require(:insurance).permit(:name, :price_cents, :company_id)
    end
  end
end

backend/app/controllers/api/insurances_controller.rb
# frozen_string_literal: true

module Api
  class InsurancesController < ApplicationController
    def index
      @insurances = Insurance.all
      render json: @insurances
    end
  end
end

backend/app/controllers/insurances_controller.rb
# frozen_string_literal: true

class InsurancesController < ApplicationController
  def index
    @insurances = Insurance.all
    @insurances = @insurances.where(price_cents: params[:min_price].to_i..) if params[:min_price].present?
    @insurances = @insurances.where(price_cents: ..params[:max_price].to_i) if params[:max_price].present?
  end

  def show
    @insurance = Insurance.find(params.fetch(:id))
    @subscription = Subscription.new(insurance: @insurance)
  end
end

backend/app/helpers/insurances_helper.rb
# frozen_string_literal: true

module InsurancesHelper
end

backend/app/views/admin/insurances/_form.html.erb
<%= form_with(model: [:admin, insurance]) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price_cents %>
    <%= form.number_field :price_cents %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= collection_select(:insurance, :company_id, Company.all, :id, :name) %>
  </div>

  <% if @insurance.errors.any? %>
    <ul>
      <% @insurance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/admin/insurances/edit.html.erb
<h1>Edit Insurance</h1>
<%= render 'form', insurance: @insurance %>

backend/app/views/admin/insurances/index.html.erb
<h1>Admin Insurances</h1>
<p>
    <ul>
        <% @insurances.each do |insurance| %>
            <li>
                <%= insurance.name %>
                <%= link_to 'Edit', edit_admin_insurance_path(insurance) %>
                <%= button_to 'Delete', admin_insurance_path(insurance), method: :delete %>
            </li>
        <% end %>
    </ul>
</p>

backend/app/views/admin/insurances/new.html.erb
<h1>New Insurance</h1>
<%= render 'form', insurance: @insurance %>