backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources "insurances", only: %i[index show] do
    resources :subscriptions, only: [:create]
  end

  namespace :admin do
    resources :insurances
    resources :claims, only: %i[index edit update]
    resources :discount_codes, only: %i[index new create]
    resources :subscriptions, only: %i[index]
  end

  namespace :api do
    resources :insurances, only: [:index]
  end

  resources :companies

  resources :subscriptions, only: %i[index] do
    resources :claims, only: %i[new create]
  end

  resources :claims, only: [:index]

  resources :vets, only: %i[index update show] do
    resources :scheduled_appointments, only: [:create]
    resources :prescriptions, only: %i[new create]
  end

  get "payments/validate_payment"

  get "payments/success"
  get "payments/error"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "insurances#index"
end

backend/app/models/vet.rb
# frozen_string_literal: true

class Vet < ApplicationRecord
  has_many :users, dependent: :destroy
  belongs_to :insurance
  has_many :scheduled_appointments, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
end

backend/app/controllers/vets_controller.rb
# frozen_string_literal: true

class VetsController < ApplicationController
  before_action :authorize_admin!

  def index
    @vets = Vet.all
  end

  def show
    @vet = Vet.find(params[:id])
    @insurance = @vet.insurance
    @scheduled_appointment = @vet.scheduled_appointments.build
  end
end

backend/app/views/vets/index.html.erb
<h1>Vet List</h1>

<ul>
  <% @vets.each do |vet| %>
    <li>
     <%= link_to vet.name, vet_path(vet)%> 
    </li>
  <% end %>
</ul>

backend/app/views/vets/show.html.erb
<p>
  <%= @vet.name %>
</p>
<p>
  Insurance: <%= @insurance.name %>
</p>

<h2>Make an appointment for this vet</h2>

<%= form_with model: [@vet, @scheduled_appointment] do |form| %>
    <div>
      <%= form.label :date %>
      <%= form.date_field :date %>
    </div>
  
    <%= form.submit "Book" %>
  <% end %>