backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources "insurances", only: %i[index show] do
    resources :subscriptions, only: [:create]
  end

  namespace :admin do
    resources :insurances
    resources :claims, only: %i[index edit update]
    resources :discount_codes, only: %i[index new create]
    resources :subscriptions, only: %i[index]
  end

  namespace :api do
    resources :insurances, only: [:index]
  end

  resources :companies

  resources :subscriptions, only: %i[index] do
    resources :claims, only: %i[new create]
  end

  resources :claims, only: [:index]

  resources :vets, only: %i[index update show] do
    resources :scheduled_appointments, only: [:create]
    resources :prescriptions, only: %i[new create]
  end

  get "payments/validate_payment"

  get "payments/success"
  get "payments/error"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "insurances#index"
end

backend/app/models/insurance.rb
# frozen_string_literal: true

class Insurance < ApplicationRecord
  has_many :subscriptions, dependent: :destroy
  has_many :discount_codes, dependent: :destroy
  has_many :vets, dependent: :destroy
  belongs_to :company

  validates :name, presence: true, uniqueness: true
  validates :price_cents, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

backend/app/controllers/admin/insurances_controller.rb
# frozen_string_literal: true

module Admin
  class InsurancesController < ApplicationController
    before_action :authorize_admin!

    def index
      @insurances = Insurance.all
    end

    def show
      @insurance = Insurance.find(params[:id])
    end

    def new
      @insurance = Insurance.new
    end

    def edit
      @insurance = Insurance.find(params[:id])
    end

    def create
      @insurance = Insurance.new(insurance_params)
      if @insurance.save
        redirect_to [:insurances, @insurances], notice: t("admin.insurances.created")
      else
        render :new
      end
    end

    def update
      @insurance = Insurance.find(params[:id])
      if @insurance.update(insurance_params)
        redirect_to admin_insurances_path, notice: t("admin.insurances.updated")
      else
        render :edit
      end
    end

    def destroy
      @insurance = Insurance.find(params[:id])
      @insurance.destroy
      redirect_to admin_insurances_path, notice: t("admin.insurances.deleted")
    end

    private

    def insurance_params
      params.require(:insurance).permit(:name, :price_cents, :company_id)
    end
  end
end

backend/app/controllers/api/insurances_controller.rb
# frozen_string_literal: true

module Api
  class InsurancesController < ApplicationController
    def index
      @insurances = Insurance.all
      render json: @insurances
    end
  end
end

backend/app/controllers/insurances_controller.rb
# frozen_string_literal: true

class InsurancesController < ApplicationController
  def index
    @insurances = Insurance.all
    @insurances = @insurances.where(price_cents: params[:min_price].to_i..) if params[:min_price].present?
    @insurances = @insurances.where(price_cents: ..params[:max_price].to_i) if params[:max_price].present?
  end

  def show
    @insurance = Insurance.find(params.fetch(:id))
    @subscription = Subscription.new(insurance: @insurance)
  end
end

backend/app/helpers/insurances_helper.rb
# frozen_string_literal: true

module InsurancesHelper
end

backend/app/views/insurances/index.html.erb
<h1>Insurances</h1>
<%= form_with url: insurances_path, method: :get, local: true do %>
    <div>
      <label for="min_price">Min Price</label>
      <%= number_field_tag :min_price, params[:min_price], id: "min_price" %>
    </div>
    <div>
      <label for="max_price">Max Price</label>
      <%= number_field_tag :max_price, params[:max_price], id: "max_price" %>
    </div>
    <%= submit_tag "Search" %>
  <% end %>
<p>
    <ul>
        <% @insurances.each do |insurance| %>
            <li>
                <%= link_to insurance.name, insurance_path(insurance) %> - (Price: <%= insurance.price_cents %>)
            </li>
        <% end %>
    </ul>
</p>

backend/app/views/insurances/show.html.erb
<p>
  <%= @insurance.name %>
</p>
<p>
  Company: <%= @insurance.company&.name %>
</p>

<h2>Sign up for this insurance</h2>

<%= form_with model: [@insurance, @subscription] do |form| %>
  <div>
    <%= form.label :starts_on %>
    <%= form.date_field :starts_on %>

    <div>
      <%= form.label :discount_code_value %>
      <%= form.text_field :discount_code_value %>
    <div>

    <% if @subscription.errors.any? %>
      <div class="error">
        <%= @subscription.errors.full_messages.join(", ") %>
      </div>
    <% end %>
  </div>

  <%= form.submit "Pay" %>
<% end %>